server:
  port: 9000
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:./db/atdb;AUTO_SERVER=TRUE
    username: autotask
    password: AT@123
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
